FROM mysql:8

# Set default locale to ja_JP.UTF-8
RUN apt-get update \
  && apt-get install -y locales \
  && echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen \
  && locale-gen ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
